In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

#CREATING A LIST

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

CONVERT LIST TO ARRAY

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(19)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [11]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10) # 1st arg< 2nd arg

array([], dtype=int64)

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-16,10)


array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [20]:
np.arange()

TypeError: arange() requires stop to be specified.

In [21]:
np.arange(10,30,5) # starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [22]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [23]:
np.arange(10,30,5,8) # Max 3 arguments (start,stop,step)

TypeError: Cannot interpret '8' as a data type

In [24]:
np.zeros(10) # parameter tuning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros( 3, dtype=int)  #hyperparameter tuning

array([0, 0, 0])

In [29]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [30]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [31]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [33]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [34]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones((3), dtype=int)

array([1, 1, 1])

In [38]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
np.two((2,3)) # zeros and ones are allowed

AttributeError: module 'numpy' has no attribute 'two'

In [42]:
rand(3,2)

NameError: name 'rand' is not defined

In [43]:
random.rand(3,2)

NameError: name 'random' is not defined

In [46]:
np.random.rand(3)

array([0.11075127, 0.89757566, 0.15873968])

In [47]:
np.random.rand(5)

array([0.94109633, 0.30360998, 0.47669118, 0.72528406, 0.16388774])

In [49]:
np.random.rand(3,5)

array([[0.35866035, 0.81470496, 0.73620859, 0.80966431, 0.80284973],
       [0.83041582, 0.5754588 , 0.49448698, 0.8950883 , 0.8696176 ],
       [0.31946576, 0.98143419, 0.30473183, 0.92980514, 0.21101521]])

In [53]:
np.random.randint(4,6) 

5

In [55]:
np.random.randint(2,20,4) 

array([ 7, 12, 13, 18], dtype=int32)

In [56]:
np.random.randint(0,9,4) 

array([8, 5, 6, 5], dtype=int32)

In [57]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [60]:
np.random.randint(-30,20,10) 

array([ -8, -29,  -8, -15, -16,  -3, -11,  11, -14,  19], dtype=int32)

In [61]:
np.random.randint(10,40,(10,10))

array([[26, 21, 10, 20, 37, 32, 19, 37, 14, 22],
       [37, 25, 27, 31, 33, 17, 35, 27, 20, 10],
       [13, 30, 25, 16, 16, 31, 26, 32, 16, 33],
       [13, 29, 15, 15, 12, 12, 35, 26, 22, 33],
       [10, 29, 38, 37, 35, 31, 28, 38, 10, 14],
       [30, 31, 26, 30, 18, 29, 25, 15, 35, 24],
       [25, 39, 23, 21, 15, 26, 33, 14, 15, 29],
       [20, 16, 15, 13, 24, 23, 38, 18, 19, 14],
       [10, 23, 15, 20, 32, 16, 11, 20, 13, 21],
       [24, 14, 30, 33, 34, 21, 33, 19, 35, 20]], dtype=int32)

In [63]:
np.random.randint(1,100,(12,12))

array([[25, 43, 34, 56, 79, 63, 16, 20, 43, 21, 69, 76],
       [78, 84, 51, 75, 44, 26, 21, 78, 34, 58, 37, 17],
       [ 9, 80, 96, 60, 34, 21, 85, 86, 13, 12, 12,  4],
       [30,  7, 30, 98, 35, 99, 69, 89, 76, 75, 25, 86],
       [16, 43, 96, 40, 92, 93, 92, 72, 16, 27, 18, 49],
       [21, 11, 29, 76, 15, 71, 23, 57, 28, 60, 77,  3],
       [37, 58, 75, 24, 55, 75, 87, 25, 37, 96, 98, 16],
       [38, 18, 86, 83, 33, 80, 73, 17, 17, 80, 44, 49],
       [79, 24, 62, 35, 15, 68, 31, 87, 41, 49, 94, 43],
       [ 1, 57, 47, 48, 74, 79, 88,  9, 26, 16,  4, 70],
       [30, 64, 87, 18, 31, 74, 25, 93, 81, 45, 60, 81],
       [93, 53, 26, 50,  6, 99, 99, 93, 76, 23, 11, 79]], dtype=int32)

In [64]:
arr

array([0, 1, 2, 3, 4, 5])

In [65]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
np.arange(1,13).reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [69]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

#slicing in Matrix

In [73]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 13, 12, 13],
       [12, 13, 13, 11],
       [15, 19, 16, 12],
       [18, 14, 12, 18],
       [13, 17, 13, 17]], dtype=int32)

In [74]:
type(b)

numpy.ndarray

In [75]:
b[:]

array([[17, 13, 12, 13],
       [12, 13, 13, 11],
       [15, 19, 16, 12],
       [18, 14, 12, 18],
       [13, 17, 13, 17]], dtype=int32)

In [78]:
b[3]

array([18, 14, 12, 18], dtype=int32)

In [79]:
b[-4]

array([12, 13, 13, 11], dtype=int32)

In [80]:
type(b)

numpy.ndarray

In [81]:
b[1:3]

array([[12, 13, 13, 11],
       [15, 19, 16, 12]], dtype=int32)

In [85]:
b[1,3]
b

array([[17, 13, 12, 13],
       [12, 13, 13, 11],
       [15, 19, 16, 12],
       [18, 14, 12, 18],
       [13, 17, 13, 17]], dtype=int32)

In [86]:
b[0,3]

np.int32(13)

In [87]:
b[1,2]

np.int32(13)

In [88]:
b[1:2]

array([[12, 13, 13, 11]], dtype=int32)

In [89]:
b[1:-1]

array([[12, 13, 13, 11],
       [15, 19, 16, 12],
       [18, 14, 12, 18]], dtype=int32)

In [90]:
b

array([[17, 13, 12, 13],
       [12, 13, 13, 11],
       [15, 19, 16, 12],
       [18, 14, 12, 18],
       [13, 17, 13, 17]], dtype=int32)

In [91]:
b[-5,3]

np.int32(13)

In [92]:
b[-5,-3]

np.int32(13)

# OPERATIONS

In [96]:
a = np.random.randint(10,20,10)
a

array([14, 16, 19, 10, 16, 14, 14, 18, 13, 13], dtype=int32)

In [98]:
id(a)

2120117285776

In [99]:
arr

array([0, 1, 2, 3, 4, 5])

In [100]:
arr2 = np.random.randint(0,100,(10,10))

In [101]:
arr2

array([[36,  8, 15, 49, 89, 40, 61, 86, 38, 30],
       [69, 28, 50, 45, 50, 73, 24, 13, 40,  2],
       [15, 60, 40, 86,  0, 63, 61, 32, 65, 37],
       [13, 79, 11, 17, 47, 61, 72, 42, 45, 45],
       [54, 59, 16, 70,  3, 58, 23, 88, 30, 54],
       [ 4, 31, 53, 96, 35, 25, 67, 97,  1, 22],
       [40, 32, 81, 66, 73, 14, 18, 81, 63, 91],
       [42, 29, 93,  4,  5,  2, 58, 98, 85, 36],
       [45, 90, 19, 13, 17, 54, 82,  4,  0, 62],
       [ 0, 13, 44, 83, 54, 85,  2, 63, 67, 29]], dtype=int32)

In [102]:
arr

array([0, 1, 2, 3, 4, 5])

In [103]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [104]:
arr[:4]

array([0, 1, 2, 3])

In [105]:
arr[::-1]

array([5, 4, 3, 2, 1, 0])

In [106]:
arr[::-2]

array([5, 3, 1])

In [107]:
arr2[::-3]

array([[ 0, 13, 44, 83, 54, 85,  2, 63, 67, 29],
       [40, 32, 81, 66, 73, 14, 18, 81, 63, 91],
       [13, 79, 11, 17, 47, 61, 72, 42, 45, 45],
       [36,  8, 15, 49, 89, 40, 61, 86, 38, 30]], dtype=int32)

In [108]:
arr2

array([[36,  8, 15, 49, 89, 40, 61, 86, 38, 30],
       [69, 28, 50, 45, 50, 73, 24, 13, 40,  2],
       [15, 60, 40, 86,  0, 63, 61, 32, 65, 37],
       [13, 79, 11, 17, 47, 61, 72, 42, 45, 45],
       [54, 59, 16, 70,  3, 58, 23, 88, 30, 54],
       [ 4, 31, 53, 96, 35, 25, 67, 97,  1, 22],
       [40, 32, 81, 66, 73, 14, 18, 81, 63, 91],
       [42, 29, 93,  4,  5,  2, 58, 98, 85, 36],
       [45, 90, 19, 13, 17, 54, 82,  4,  0, 62],
       [ 0, 13, 44, 83, 54, 85,  2, 63, 67, 29]], dtype=int32)

In [109]:
arr2[:-3]

array([[36,  8, 15, 49, 89, 40, 61, 86, 38, 30],
       [69, 28, 50, 45, 50, 73, 24, 13, 40,  2],
       [15, 60, 40, 86,  0, 63, 61, 32, 65, 37],
       [13, 79, 11, 17, 47, 61, 72, 42, 45, 45],
       [54, 59, 16, 70,  3, 58, 23, 88, 30, 54],
       [ 4, 31, 53, 96, 35, 25, 67, 97,  1, 22],
       [40, 32, 81, 66, 73, 14, 18, 81, 63, 91]], dtype=int32)

In [110]:
arr2[0:10:3]

array([[36,  8, 15, 49, 89, 40, 61, 86, 38, 30],
       [13, 79, 11, 17, 47, 61, 72, 42, 45, 45],
       [40, 32, 81, 66, 73, 14, 18, 81, 63, 91],
       [ 0, 13, 44, 83, 54, 85,  2, 63, 67, 29]], dtype=int32)

In [111]:
arr

array([0, 1, 2, 3, 4, 5])

In [112]:
arr.mean()

np.float64(2.5)

In [113]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [114]:
arr.mod()

AttributeError: 'numpy.ndarray' object has no attribute 'mod'

In [119]:
from numpy import * 
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# INDEXING

In [129]:
import numpy as np


In [132]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
row = 4
col = 5

In [123]:
col

5

In [124]:
row

4

In [133]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [134]:
mat[row,col]

np.int64(45)

In [135]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
col = 6

In [137]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [138]:
mat[:, col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [139]:
mat[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [140]:
mat[:, -2]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [141]:
row

4

In [142]:
mat[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [143]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [144]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [145]:
mat[1:2,2:4]

array([[12, 13]])

In [146]:
mat[2:3,2:3] 

array([[22]])

# MASKING

In [148]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [149]:
id(mat)

2120118673808

In [150]:
mat[ mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [151]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [152]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [154]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [155]:
mat[mat==50]

array([50])