#  ARRAY CREATION FUNCTIONS

In [1]:
import numpy as np

In [3]:
#Create an array from a list
a = np.array([1,2,3])
print(" Array a:", a)

 Array a: [1 2 3]


In [4]:
#create an array with evenly spaced values
b = np.arange(0, 10, 2)
print("Array b:", b)

Array b: [0 2 4 6 8]


In [5]:
b = np.arange(0, 10, 3)
print("Array b:", b)

Array b: [0 3 6 9]


In [6]:
# Create an array filled with zeros

d = np.zeros((2,3), dtype=int)
print("Array d:\n", d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [8]:
d = np.zeros((2,3))
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Create an array filled with ones

d = np.ones((2,3), dtype=int)
print("Array d:\n", d)

Array d:
 [[1 1 1]
 [1 1 1]]


In [10]:
d = np.ones((3,2))
print("Array d:\n", d)

Array d:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
#create an Identity matrix
f = np.eye(4)
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# ARRAY MANIPULATION FUNCTIONS

In [14]:
#Reshape an array

a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (1,3)) #Reshape to 1*3
print("reshaped array:", reshaped)

reshaped array: [[1 2 3]]


In [15]:
#Reshape an array

a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (3,1)) #Reshape to 1*3
print("reshaped array:", reshaped)

reshaped array: [[1]
 [2]
 [3]]


In [17]:
# Flatten an array
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [18]:
# Flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8]])
flattened = np.ravel(f1) #Flatten 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4 5 6 7 8]


In [20]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [21]:
#Stacks arrays vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print("stacked arrays:\n", stacked)


stacked arrays:
 [[1 2]
 [3 4]]


import numpy as np